= Pflichtenheft - Flashcards
Mostbauer Julian, Brunner Jan, Kerimcan Yagci, Parzer Lorenz
1.0.0, {docdate}
:sectnums:

== Ausgangssituation

Viele junge Personen besuchen Schulen, Universitäten oder andere Lehranstalten, in welchen sie sich für ihre Zukunft weiterbilden. Um ihr Wissen beweisen zu können, müssen sie zahlreiche Prüfungen bestehen.

== Istzustand

Derzeit lernen die meisten Personen von Zusammenfassungen oder erstellen sich selbst Lernkarten und lernen mit denen. Ebenfalls lernen viele Personen mit Lernplattformen.

== Problemstellung

Analoge meist selbstgemachte Lernkarteikarten bringen einen großen Zeitaufwand als auch ein Verwaltungsproblem mit sich. Zudem sind die meisten Lernplattformen kostenpflichtig. Diese Plattformen haben meist auch einen Free-trail, aber dieser ist meistens sehr begrenzt und verfügt über nicht so viele Funktionen.

== Aufgabenstellung

=== Funktionale Anforderungen

* **Stapelverwaltung**: Benutzer können Lernkarten-Stapel (Decks) erstellen, um verschiedene Themen (z. B. Englisch, Informatik) zu trennen.
* **Lernmodus**: Benutzer werden über die Lernkarten abgefragt.
* **Fortschritt speichern**: Das System speichert, welche Karten bereits gelernt wurden, um den Fortschritt anzuzeigen.
* **Filter/Suche**: Benutzer können nach bestimmten Stapeln oder Karten suchen.

image::https://img.plantuml.biz/plantuml/dpng/NP7FQiCm38VlUWgHUmlhNnWbjAJTUT3r0OIj92Qk4spvKCRUVKwNXcG-_SJtIRRmCGXvYNSBbaj1QT6RgXRKnhCIqpe8ZN4TURfZHwgXYg_oi8mz9bTP1Y0bhSTRO8yKC08C8cOVbaAjoEk0fwxBy1imdHXOKKYuy4p2U6RLP7thhNYR2oUjiKZj_RicrcfkNRIHfpRWzHoVsNAwPI9ivi9LedvCvs__yJgMfVsR40PbDrU-V5ePFtrRUGulPmy_014NY_ovsIkjnhGUqsPCsp7j0LA9osLVxF0T3mVZb8sQynoEx7JwjLy0[UCD, 600]

=== Nicht funktionale Anforderungen (NFA)

* **Bedienbarkeit**: Die App soll so einfach wie möglich gestaltet sein, damit man ohne lange Einarbeitung direkt anfangen kann zu lernen.
* **Stabilität**: Die Anwendung soll sowohl auf dem PC als auch auf dem Tablet oder Smartphone gut lesbar und bedienbar sein.

== Ziele

* Lernen mit Karteikarten kostenlos ermöglichen
* Zeitaufwand beim Erstellen und Verwalten der Karten zu vermindern
* Unterstützung der Nutzer um die Organisation der Lerninhalte zu verbessern durch einfacher Stapelverwaltung

== Mengengerüst

Ein Schüler an unserer Schule hat um die 15 Fächer für die er lernen muss. Im Schnitt kann man mit 30 Flashcards pro Fach rechnen, wodurch ein Nutzer auf ca. 450 FLashcards pro Schuljahr kommt. 

Datenbestände: Text, Bilder und Audio.

== Rahmenbedingungen

=== Technisch
- JavaFX App

=== Zetilich
- Abschluss des Projektes vor dem Ende des Schuljahres