= Pflichtenheft - Flashcards
Mostbauer Julian, Brunner Jan, Kerimcan Yagci, Parzer Lorenz
1.0.0, {docdate}
:sectnums:

== Ausgangssituation

Viele junge Personen besuchen Schulen, Universitäten oder andere Lehranstalten, in welchen sie sich für ihre Zukunft weiterbilden. Um ihr Wissen beweisen zu können, müssen sie zahlreiche Prüfungen bestehen.

== Istzustand

Derzeit lernen die meisten Personen durch Zusammenfassungen oder das Erstellen von eigenen Lernkarten oder lernen mit denen. Ebenfalls lernen viele Personen mit Lernplattformen.

== Problemstellung

Analoge meist selbstgemachte Lernkarteikarten bringen einen großen Zeitaufwand als auch ein Verwaltungsproblem mit sich. Zudem sind die meisten Lernplattformen kostenpflichtig. Diese Plattformen haben meist auch einen Free-trail, aber dieser ist meistens sehr begrenzt und verfügt über nicht so viele Funktionen.
Ein gutes Beispiel dafür ist Quizlet. Früher waren alle Funktionen dieser App kostenlos, aber jetzt verstecken sich die sehr viele Funktionen aber hinter einen kostenpflichtigen Plan.

*Hier eine kurze Auflistung der kostenpflichtigen Features:*

* Lern-Modus
* Test-Modus
* Q-Chat
* Magic-Notes
* KI-Übungstests
* Eigene Bilder
* Eigene Audio Aufnahmen
* Formatierung von Text
* Offline Lernen
* Smart Grading
* Werbefreiheit

== Aufgabenstellung

Das Ziel des Projekts ist eine einfache App, mit der man digitale Lernkarten erstellen und verwalten kann. Man soll seine Karten in verschiedene Stapel (Decks) einsortieren können, zum Beispiel für verschiedene Schulfächer. Die App soll kostenlos sein und dabei helfen, schneller und organisierter zu lernen, ohne dass man einen riesigen Stapel aus Papier mit sich herumtragen muss.

image::https://img.plantuml.biz/plantuml/dpng/NP7FQiCm38VlUWgHUmlhNnWbjAJTUT3r0OIj92Qk4spvKCRUVKwNXcG-_SJtIRRmCGXvYNSBbaj1QT6RgXRKnhCIqpe8ZN4TURfZHwgXYg_oi8mz9bTP1Y0bhSTRO8yKC08C8cOVbaAjoEk0fwxBy1imdHXOKKYuy4p2U6RLP7thhNYR2oUjiKZj_RicrcfkNRIHfpRWzHoVsNAwPI9ivi9LedvCvs__yJgMfVsR40PbDrU-V5ePFtrRUGulPmy_014NY_ovsIkjnhGUqsPCsp7j0LA9osLVxF0T3mVZb8sQynoEx7JwjLy0[UCD, 600]

=== Funktionale Anforderungen

* **Stapelverwaltung**: Benutzer können Lernkarten-Stapel (Decks) erstellen, um verschiedene Themen (z. B. Englisch, Informatik) zu trennen.
* **Lernmodus**: Benutzer werden über die Lernkarten abgefragt.
* **Fortschritt speichern**: Das System speichert, welche Karten bereits gelernt wurden, um den Fortschritt anzuzeigen.
* **Filter/Suche**: Benutzer können nach bestimmten Stapeln oder Karten suchen.


=== Nicht funktionale Anforderungen (NFA)

* **Bedienbarkeit**: Die App soll so einfach wie möglich gestaltet sein, damit man ohne lange Einarbeitung direkt anfangen kann zu lernen.
* **Stabilität**: Die Anwendung soll sowohl auf dem PC als auch auf dem Tablet oder Smartphone gut lesbar und bedienbar sein.

== Ziele

* Lernen mit Karteikarten kostenlos ermöglichen
* Zeitaufwand beim Erstellen und Verwalten der Karten zu vermindern
* Unterstützung der Nutzer um die Organisation der Lerninhalte zu verbessern durch einfacher Stapelverwaltung

== Mengengerüst

Ein Schüler an unserer Schule hat um die 15 Fächer, für die er lernen muss. Im Schnitt kann man mit 30 Flashcards pro Fach rechnen, wodurch ein Nutzer auf ca. 450 Flashcards pro Schuljahr kommt.

Datenbestände: Text, Bilder und Audio.

== Rahmenbedingungen

=== Technisch
- JavaFX App

=== Zeitlich
- Abschluss des Projektes vor dem Ende des Schuljahres
