= Pflichtenheft - Flashcards
Mostbauer Julian, Brunner Jan, Kerimcan Yagci, Parzer Lorenz
1.0.0, {docdate}
:sectnums:

== Ausgangssituation

Viele junge Personen besuchen Schulen oder Universitäten, in welchen sie sich für ihre Zukunft weiterbilden. Um ihr Wissen beweisen zu können, müssen sie zahlreiche Prüfungen bestehen.

== Istzustand

Derzeit lernen die meisten Personen von Zusammenfassungen oder erstellen sich selbst Lernkarten und lernen mit denen. Ebenfalls lernen viele Personen mit Lernplattformen.

== Problemstellung

Analoge meist selbstgemachte Lernkarteikarten bringen einen großen Zeitaufwand als auch ein Verwaltungsproblem mit sich. Zudem sind die meisten Lernplattformen kostenpflichtig, diese Plattformen haben meist einen Free-trail, aber dieser ist meistens sehr begrenzt und verfügt über nicht so vielen Funktionen.

== Aufgabenstellung

=== Funktionale Anforderungen

=== Nicht funktionale Anforderungen (NFA)

== Ziele

== Mengengerüst

Ein Schüler an unserer Schule hat um die 15 Fächer für die er lernen muss. Im Schnitt kann man mit 30 Flashcards pro Fach rechnen, wodurch ein Nutzer auf ca. 450 FLashcards pro Schuljahr kommt. 

Datenbestände: Text, Bilder und Audio.

== Rahmenbedingungen

=== Technisch
- JavaFX App

=== Zetilich
- Abschluss des Projektes vor dem Ende des Schuljahres